### ISSUE TITLE
Inquiry about possible naked list of IPs for PFsense integration

### ISSUE THREAD

**Issue by Lefuneste83** [Lars-/PIA-servers#10]
Hi there

Thanks a lot for this useful list.
As I try to integrate it with my router (PFsense), in order to define specific routes for VPN traffic, I realize that your export.csv file does not suite well with the import filter of PFsense.
I have manually processed your csv file into a simple txt file with only IP addresses (one IP address per line with CR at the end of each line). This way PFsense can parse it and use it as an alias. The process would be similar with other firewall (OPNsense for instance).

But as this list is dynamic and changes regularly, I wonder if it would be possible for you to publish such a simple txt file in order to have firewall directly subscribe to it.

Thanks

**Comment by mmomjian** [comment]
For anyone still looking, this can be done with the following command:

`curl https://raw.githubusercontent.com/Lars-/PIA-servers/master/export.csv | tail -n +2 | cut -d, -f1 > export_iponly`
