### ISSUE TITLE
Missing Regions

### ISSUE THREAD

**Issue by GarrettEHill** [Lars-/PIA-servers#11]
First off this is awsome...

Some regions that are missing:

- US Phoenix
- US Dallas
- US Miami

**Comment by leacostae** [comment]
And some countries like Bolivia,Chile, Colombia, Costa Rica, Ecuador, Guatemala, Peru, Uruguay

**Comment by Lars-** [comment]
Sorry for the exremely late response, I didn't get a notification apparently... 

All regions that OpenVPN supplies in their zip file should be available here.
