### ISSUE TITLE
Question: How reliable is the provided information within this repository?

### ISSUE THREAD

**Issue by Avnsx** [Lars-/PIA-servers#8]
So judging by the ReadMe the way you're obtaining these servers, is by just letting your bot repeadetly connect and disconnect from the server nodes is that correct?

Do you think with this strategy you've actually indexed a high percentage of the total servers by them? Various online sources state they own 30k+ servers, within this repo are only listed 17k

**Comment by Lars-** [comment]
Sorry, I didn't receive a notification for this issue.

No, I don't connect to the servers at all. I only do dns requests, I do it every minute for all the locations. The ips in this repo are the ones that were provided in the last 2 weeks (if I remember correctly). So, there may be 30k servers, but they only use the amount that you see in this repo.
